title: STALKING LENA 
author: Lena Park
email: lenapark0122@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Lena Park and I am a junior at East Brunswick High School.  I can eat a whole cheesecake on my own in one sitting:) 
  I am also a varsity athelete and hope to get recruited to a liberal arts school.

# social links
instagram_username: l.ena116
github_username:  lena116

show_excerpts: false # set to false to remove excerpts on the homepage
